### ISSUE TITLE
EPUB and CBZ do not render correctly

### ISSUE THREAD

**Issue by returntrip** [Yetangitu/owncloud-apps#58]
Does not seem to work for me. EPUB files render the first couple of pages but then stops rendering. CBZ files do not render. I see several of these errors in the log file:

: ```Undefined index: title at /usr/share/webapps/nextcloud/apps/files_reader/templates/epubreader.php#37```

**Comment by linuxpng** [comment]
Can confirm that CBRs are not working as well.

**Comment by Yetangitu** [comment]
Which browser, and which publications? Does this go for all files you feed it or only certain individual files? Can you post an example file somewhere?

**Comment by Psychodogg** [comment]
Any CBZ file i try to open looks like

https://cloud.myfunhouse.net/index.php/s/qlaHzFpKvrRlzB2

EPUB files work fine

**Comment by Yetangitu** [comment]
Which browser? Any messages in the console?

It works fine here, in Firefox, Chromium, Opera. Parts work fine in Edge, others - like the CBx renderer - still have problems. I currently do not have access to anything Apple so I can not test in Safari/iOS or Safari/MacOS. Knowing that Safari is the 'new IE' it would not surprise me to hear your using it.

**Comment by Psychodogg** [comment]
Chrome and it is up to date

Error Log


Error | PHP | Undefined index: title at /var/www/clients/client1/web4/web/apps/files_reader/templates/cbreader.php#37 | 2018-01-18T10:51:07-0500
-- | -- | -- | --
Error | PHP | Undefined variable: dllink at /var/www/clients/client1/web4/web/apps/files_reader/templates/cbreader.php#15 | 2018-01-18T10:51:07-0500
Error | PHP | Undefined index: title at /var/www/clients/client1/web4/web/apps/files_reader/templates/cbreader.php#37 | 2018-01-18T10:48:24-0500
Error | PHP | Undefined variable: dllink at /var/www/clients/client1/web4/web/apps/files_reader/templates/cbreader.php#15 | 2018-01-18T10:48:24-0500
Error | PHP | Undefined index: title at /var/www/clients/client1/web4/web/apps/files_reader/templates/epubreader.php#37 | 2018-01-18T10:48:14-0500

**Comment by Yetangitu** [comment]
Should be fixed in 1.1.4, soon to be released...

**Comment by Psychodogg** [comment]
wow you work fast!

Thanks for all your hard work.

**Comment by Psychodogg** [comment]
I have updated to 1.1.4 but still see the issue. I have tested in FireFox, IE, and Chrome.

This is making me thing I may have something configured wrong maybe.

**Comment by Yetangitu** [comment]
Check those template files on your server and compare them to what you see in the log. If it still complains about undefined indexes while the files on disk have changed you need to restart your PHP container server (php-fpm, your webserver or whatever means you use to run NC).

This is what the files should look like:

https://github.com/Yetangitu/owncloud-apps/blame/master/files_reader/templates/cbreader.php

https://github.com/Yetangitu/owncloud-apps/blame/master/files_reader/templates/epubreader.php

**Comment by Yetangitu** [comment]
Any updates on this issue?

**Comment by onliniak** [comment]
CBZ no work on Firefox and Chrome due to protection policy ?

Latest chrome + https + http 2.0 + nextcloud 12.04

I can load example file with 200 OK code (goldenboy.cbz from Google Drive comic reader) but cannot display it.

/index.php/apps/files/:1 Error parsing header X-XSS-Protection: 1; mode=block, 1; mode=block: expected semicolon at character position 14. The default protections will be applied.
core.js:7 JQMIGRATE: Migrate is installed, version 1.4.0
jsxc.min.js:13 State changed to INITIATING
jsxc.min.js:13 Try to relogin
jsxc.min.js:13 Logout was forced or I found no valid jid
jsxc.min.js:13 State changed to SUSPEND
6
jsxc.min.js:13 [WARN] Unable to create user prefix
soundmanager2-jsmin.js:34 SoundManager 2: No Flash detected. Trying HTML5-only mode.
soundmanager2-jsmin.js:34 SoundManager V2.97a.20170601 (HTML5-only mode) + html5PollingInterval (200ms)
soundmanager2-jsmin.js:34 SoundManager 2 HTML5 support: mp3 = true, mp4 = true, ogg = true, opus = true, wav = true, flac = true
soundmanager2-jsmin.js:34 SoundManager 2: Ready. ✓
cloud.example.com/:1 Error parsing header X-XSS-Protection: 1; mode=block, 1; mode=block: expected semicolon at character position 14. The default protections will be applied.
cloud.example.com/:7 Refused to set the document's base URI to 'https://cloud.example.com/apps/files_reader/' because it violates the following Content Security Policy directive: "base-uri 'none'".
cloud.example.com/:11 Resource interpreted as Stylesheet but transferred with MIME type text/html: "https://cloud.example.com/index.php/apps/files/".
cloud.example.com/:12 Resource interpreted as Stylesheet but transferred with MIME type text/html: "https://cloud.example.com/index.php/apps/files/".
ready.js?v=1.1.4.0047:28 /apps/files_reader/
archive.js?v=1.1.4.0047:252 [Deprecation] The 'child-src' directive is deprecated and will be removed in M60, around August 2017. Please use the 'script-src' directive for Workers instead. See https://www.chromestatus.com/features/5922594955984896 for more details.
archive.js?v=1.1.4.0047:255 Worker error: message = Uncaught SyntaxError: Unexpected token <
archive.js?v=1.1.4.0047:256 Uncaught 
ErrorEvent {isTrusted: true, message: "Uncaught SyntaxError: Unexpected token <", filename: "https://cloud.example.com/index.php/apps/files_reader/vendor/bitjs/archive/unzip.js", lineno: 1, colno: 1, …}
unzip.js:1 Uncaught SyntaxError: Unexpected token <
﻿

​

**Comment by seiichiro0185** [comment]
I also have this Problem. The template files on my disk are like the ones in GIT (also replaced the ones in my Installation with the ones in GIT). I'm on Version 1.1.5.

The Console of my Firefox 57 does say that "Some Resources where blocked due to Content Security Policy being 'base-uri="none"'. This seems to be the Problem, if I change this in the Corresponding file in Nextcloud Core to be "base-uri='self'" it starts to work as expected.

Changing the Nextcloud source does not seem to be the correct way to do this, but I haven't found why Nextcloud does set the CSP like that. I don't know if there is a way for a plugin to change this behavior (or if there should be), since I didn't investigate Nextclouds CSP mechanism further.

**Comment by Yetangitu** [comment]
Hm, that part of the CSP (`base-uri "none"`) is set in `EmptyContentSecurityPolicy::buildPolicy()` (`<NC_ROOT>/lib/public/AppFramework/Http/EmptyContentSecurityPolicy.php:336") and there is no official way to change it that I know of.

The templates use `<base>` (`<base href="<?php p($urlGenerator->linkTo('files_reader',''));?>">`) to ensure all relative links point in the right direction. Try to remove that line in the template and check if it works.

As to why this causes problems for some but not for others, good question. I test with recent versions of Firefox, Seamonkey, Chromium and several Android browsers, it 'works for me'.

**Comment by seiichiro0185** [comment]
I tried changing removing the "<base...  >" line you mentioned from the templates (after changing back EmptyContentSecurtiyPolicy.php to the default), but it doesn't help, Viewing CBR/CBZ is still broken as long as I don't change EmptyContentSecurtiyPolicy.php to return "self".
The strange thing is that Viewing EPUB Files works without any of the modifications...

**Comment by Yetangitu** [comment]
I see the same message in the console, this does not seem to be the reason for Reader not working as it does work here. I guess I can remove the `<base>` from the template, it was there to make sure relative links were predictable over all installations, that in turn was necessary to get JS worker scripts to load without problems on all browsers. I solved that problem in a different way.

Anyway, your problem lies somewhere else.

**Comment by seiichiro0185** [comment]
Looks like it, but it definitely has something to do with the CSP stuff, since changing the headers in the Nextcloud Core does resolve it. Maybe my Firefox is set to be extra picky about the CSP headers or something along those lines, although it also happens with Chrome, and on multiple Machines, so it doesn't seem to be a Browser specific problem. Maybe I'm missing something in my Nextcloud config or misconfigured my webserver somehow.
I'll see if I can find anything else regarding the CSP stuff in Nextcloud, but it seems there is not to much info about this around the net.

**Comment by Yetangitu** [comment]
Maybe your web server adds something to the headers which stops it working? Can you post the request headers here?

**Comment by Psychodogg** [comment]
sorry i have been away and was not able to get into troubleshooting

I have tested rolling back the versions and none are fixing this so it would seem something in the NC core it causing this issue.

**Comment by Yetangitu** [comment]
FYI, this is what it looks like here, for comparison:

```
HTTP/2.0 200 OK
cache-control: no-store, no-cache, must-revalidate
content-length: 12403911
content-security-policy: default-src 'none';
content-type: application/x-cbr
date: Mon, 22 Jan 2018 19:46:54 GMT
etag: "542336b864034"
expires: Thu, 19 Nov 1981 08:52:00 GMT
last-modified: Sun, 23 Oct 2011 09:46:49 GMT
oc-etag: "542336b864034"
pragma: no-cache
server: nginx/1.10.2
strict-transport-security: max-age=15552000; includeSubDomains
x-content-type-options: nosniff
x-download-options: noopen
X-Firefox-Spdy: h2
x-frame-options: SAMEORIGIN
x-permitted-cross-domain-policies: none
x-robots-tag: none
x-xss-protection: 1; mode=block
```

**Comment by Yetangitu** [comment]
Which version of NC?

**Comment by seiichiro0185** [comment]
Well.. seems like the problem really is the webserver (nginx in my case). I just replaced my nginx config on my Test-Nextcloud at home with the example nginx config from the Nextcloud Administration Manual for NC12, and one restart later, it suddenly started working without any modifications to the Nextcloud Core files.... So It looks like some configuration f**ckup on my side, and not a problem in the Plugin.

Anyways thanks for helping me debug this :)

For the record, this is NC 12.0.4 running on PHP-FPM 7.1 with nginx

**Comment by Yetangitu** [comment]
More or less the same configuration as I use, and good that it works now. Closing this issue...
